---
title: "Working Code Document"
author: "Group 7"
date: "`r Sys.Date()`"
output: html_document
---

\# Data Wrangling

```{r data_wrangling}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(patchwork)
library(readr)
library(ggdag)
library(mice)
library(VIM)
library(naniar)


load(file='obesity.Rda')

other_outcomes <- c("diabetes", "MI", "angina", "stroke", "death") 

# Data wrangling: remove unused outcomes + rows with NAs
data <- obesity %>%
  select(!other_outcomes) %>%
  na.omit()

# Mutate to binary 
obesity <- data %>%
  mutate(medhyper = case_when(
    medhyper == "no" ~ 0,
    medhyper == "yes" ~ 1,),
    CVD = case_when(
      CVD == "No" ~ 0,
      CVD == "Yes" ~ 1,),
    medstatin = case_when(
    medstatin == "no" ~ 0,
    medstatin == "yes" ~ 1,),
    medglucose = case_when(
    medglucose == "no" ~ 0,
    medglucose == "yes" ~ 1,),
    current.smoking = case_when(
      current.smoking == "no" ~ 0,
      current.smoking == "yes" ~ 1,))

## Transform variables 
# Adiposity
plot(obesity$bmi, obesity$waist)
adiposity_model <- lm(bmi ~ waist, data = obesity)
summary(adiposity_model)

obesity$adiposity <- scale(obesity$bmi) + scale(obesity$waist)

# BP
plot(obesity$SYSBP, obesity$DIABP)
bp_model <- lm(SYSBP ~ DIABP, data = obesity)
summary(bp_model)

obesity$MAP <- obesity$DIABP + (obesity$SYSBP - obesity$DIABP)/3

# Alcohol 
obesity$alcohol <- case_when(obesity$alcohol > 5 ~ 6,
          obesity$alcohol == 5 ~ 5,
          obesity$alcohol == 4 ~ 4,
          obesity$alcohol == 3 ~ 3,
          obesity$alcohol == 2 ~ 2,
          obesity$alcohol == 1 ~ 1,
          obesity$alcohol == 0 ~ 0) 

# SES
obesity$SES <- ifelse(obesity$income == "low or normal" & obesity$education == "other", 1,
                      ifelse(obesity$education == "high" & obesity$income == "high", 3, 2))

# Comorbidities
obesity = obesity %>% 
  mutate(comorbidities = case_when(
    medstatin == 1 & medglucose == 1 ~ "2",
    medstatin == 1 | medglucose == 1 ~ "1",
    medstatin == 0 & medglucose == 0 ~ "0"))

# convert the comorbidities into factor
obesity$comorbidities = as.factor(obesity$comorbidities)


# Quick look if populations are comparable for pre-treatment covariates
## Age
p1 <- ggplot(obesity, aes(x = age, fill = factor(medhyper))) +
  geom_density(alpha = 0.5) +
  labs(x = "Age") +
  scale_fill_manual(
    name = "MedHyper",
    values = c("0" = "#F8766D", "1" = "#00BFC4")) +
  theme(legend.position = "none",
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())

## Sex
p2 <- ggplot(obesity, aes(x = factor(sex), fill = factor(medhyper))) +
  geom_bar(position = "fill") +
  labs(x = "Sex") +
  scale_fill_manual(
    name = "MedHyper",
    values = c("0" = "#F8766D", "1" = "#00BFC4")) +
  theme(legend.position = "none",
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())


## Adiposity 
p3 <- ggplot(obesity, aes(x = adiposity, fill = factor(medhyper))) +
  geom_density(alpha = 0.5) +
  labs(x = "Adiposity") +
  scale_fill_manual(
    name = "MedHyper",
    values = c("0" = "#F8766D", "1" = "#00BFC4")) +
  theme(legend.position = "none",
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())


## BP
p4 <- ggplot(obesity, aes(x = MAP, fill = factor(medhyper))) +
  geom_density(alpha = 0.5) +
  labs(x = "MAP") +
  scale_fill_manual(
    name = "MedHyper",
    values = c("0" = "#F8766D", "1" = "#00BFC4")) +
  theme(legend.position = "none",
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())

## Smoking
p5 <- ggplot(obesity, aes(x = factor(current.smoking), fill = factor(medhyper))) +
  geom_bar(position = "fill") +
  labs(x = "Smoking") +
  scale_fill_manual(
    name = "MedHyper",
    values = c("0" = "#F8766D", "1" = "#00BFC4")) +
  theme(legend.position = "none",
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())

## Alcohol
p6 <- ggplot(obesity, aes(x = factor(alcohol), fill = factor(medhyper))) +
  geom_bar(position = "fill") +
  labs(x = "Alcohol") +
  scale_fill_manual(
    name = "MedHyper",
    values = c("0" = "#F8766D", "1" = "#00BFC4")) +
  theme(legend.position = "none",
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())

## Comorbidities
p7 <- ggplot(obesity, aes(x = factor(comorbidities), fill = factor(medhyper))) +
  geom_bar(position = "fill") +
  labs(x = "Comorbidities") +
  scale_fill_manual(
    name = "MedHyper",
    values = c("0" = "#F8766D", "1" = "#00BFC4")) +
  theme(legend.position = "none",
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())

# SES
p9 <- ggplot(obesity, aes(x = factor(SES), fill = factor(medhyper))) +
  geom_bar(position = "fill") +
  labs(x = "SES") +
  scale_fill_manual(
    name = "MedHyper",
    values = c("0" = "#F8766D", "1" = "#00BFC4")) +
  theme(legend.position = "none",
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())

# Combine plots
pop_plots <- list(p1, p2, p3, p4, p5, p6, p7, p9)

wrap_plots(pop_plots, nrow = 3) +
plot_layout(guides = "collect") &
theme(legend.position = "bottom")

```

## DAG

```{r dag}
library(ggdag)
library(dagitty)
library(ggplot2)

obesity_dag <- dagify(
  Comorbidities ~ Age + Adiposity + Sex + SES,
  Adiposity ~ Age + Sex + SES,
  BP ~ Age + Sex + Adiposity + Smoking + Alcohol + SES + Comorbidities,
  MedHyper ~ BP + SES + Age + Sex + Smoking + Alcohol + Adiposity + Comorbidities,
  CVD ~ Age + Sex + Smoking + Alcohol + Adiposity + BP + MedHyper + SES + Comorbidities,
  
  exposure = "MedHyper",
  outcome = "CVD",
  
  coords = list(
    x = c(
      Age = 2,
      Sex = 6,
      Smoking = 2.5,
      Alcohol = 5.5,
      Adiposity = 2.5,
      SES = 4,
      BP = 5.5,
      MedHyper = 2,
      CVD = 6,
      Comorbidities = 4
    ),
    
    y = c(
      Age = 5,
      Sex = 5,
      Smoking = 1,
      Alcohol = 1,
      Adiposity = 4,
      SES = 0,
      BP = 4,
      MedHyper = 2.5,
      CVD = 2.5,
      Comorbidities = 3
    )
  )
)

ggdag(obesity_dag, text_size = 1.8) +
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    panel.background = element_blank())



adjustmentSets(obesity_dag)


ggdag_adjustment_set(
  obesity_dag,
  text = TRUE,
  text_size = 2.4
) +
  theme(
    legend.position = "bottom",
    legend.text.position = "bottom",
    legend.title = element_blank(),
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    panel.background = element_blank()
    )
```

# Identifying confounders

## T-tests

```{r t-tests}
t.test(obesity$age ~ obesity$medhyper) #significant
t.test(obesity$adiposity ~ obesity$medhyper) #significant
t.test(obesity$MAP ~ obesity$medhyper) #significant
```

## Chi square

```{r chi square}
chisq.test(obesity$sex, obesity$medhyper) #significant 
chisq.test(obesity$current.smoking, obesity$medhyper) #not significant 
chisq.test(obesity$alcohol, obesity$medhyper) #significant 
chisq.test(obesity$SES, obesity$medhyper) #significant 
chisq.test(obesity$comorbidities, obesity$medhyper) #significant 
```

# Outcome regression

```{r outcome_regression}
glm = glm(CVD ~ medhyper + 
            age + medhyper*age +
            sex + medhyper*sex +
            adiposity + medhyper*adiposity + 
            MAP + medhyper*MAP +
            current.smoking + medhyper*current.smoking +
            alcohol + medhyper*alcohol +
            comorbidities + medhyper*comorbidities +
            SES + medhyper*SES,
          data = obesity, family = binomial)
summary(glm)
```

# G-formula

## Step 1

```{r g-formula}
g_model = glm(CVD ~ medhyper + 
            age + medhyper*age +
            sex + medhyper*sex +
            adiposity + medhyper*adiposity + 
            MAP + medhyper*MAP +
            current.smoking + medhyper*current.smoking +
            alcohol + medhyper*alcohol +
            comorbidities + medhyper*comorbidities +
            SES + medhyper*SES,
          data = obesity, family = binomial)
summary(g_model)
```

## Step 2

```{r step 2}
obesity1 = obesity
obesity1$medhyper = 1
YE1 = predict(g_model, newdata = obesity1, type="response")
mean_YE1 = mean(YE1, na.rm = T)
```

```{r step 2.5}
obesity0 = obesity
obesity0$medhyper = 0
YE0 = predict(g_model, newdata = obesity0, type="response")
mean_YE0 = mean(YE0, na.rm = T)

```

## Step 3

```{r step 3}
mean_YE1- mean_YE0 #average treatment effect (ATE)

(mean_YE1/(1-mean_YE1))/(mean_YE0/(1-mean_YE0)) #causal odds ratio
```

# Bootstrap to get the CI

```{r bootstrap}
set.seed(123)
B = 1000
ATE_boot = numeric(B)
OR_boot  = numeric(B)

n = nrow(obesity)

for (b in 1:B) {

  #Resample data
  index = sample(1:n, n, replace = TRUE) 
  data_b = obesity[index, ] 

  #Refit model
g_model_b = glm(CVD ~ medhyper + 
            age + medhyper*age +
            sex + medhyper*sex +
            adiposity + medhyper*adiposity + 
            MAP + medhyper*MAP +
            current.smoking + medhyper*current.smoking +
            alcohol + medhyper*alcohol +
            comorbidities + medhyper*comorbidities +
            SES + medhyper*SES,
          data = data_b, family = binomial)
  #Predict medhyper = 1
  data1 = data_b
  data1$medhyper = 1
  p1 = predict(g_model_b, newdata = data1, type="response")
  m1 = mean(p1, na.rm = T)

  #Predict medhyper = 0
  data0 = data_b
  data0$medhyper = 0
  p0 = predict(g_model_b, newdata = data0, type="response")
  m0 = mean(p0, na.rm = T)

  #Store estimands
  ATE_boot[b] = m1 - m0
  OR_boot[b]  = (m1/(1-m1)) / (m0/(1-m0))
}

mean(ATE_boot, na.rm = T)
mean(OR_boot, na.rm = T)

quantile(ATE_boot, c(0.025, 0.975), na.rm = T)
quantile(OR_boot,  c(0.025, 0.975), na.rm = T)
```

## Positivity

```{r positivity}
table(obesity$sex, obesity$medhyper)
table(obesity$current.smoking, obesity$medhyper)
table(obesity$alcohol, obesity$medhyper)
table(obesity$SES, obesity$medhyper)
table(obesity$comorbidities, obesity$medhyper)
```

## Visualization

```{r visualisation}
# Plots (can find prettier colours at https://r-charts.com/colors/)
boots_df <- data.frame(
  ATE = ATE_boot,
  OR = OR_boot
)

ATE_plot <- ggplot(boots_df, aes(x = ATE)) +
  geom_histogram(bins = 20, fill = "grey85") +
  labs(title = "Bootstrap ATE",
       x = "Risk Difference",
       y = NULL) +
  geom_vline(
    aes(xintercept = mean(ATE_boot)),
    color = "slateblue4", linewidth = 0.5) +
  geom_vline(
    aes(xintercept = quantile(ATE_boot, 0.025)),
    color = "slateblue1", linewidth = 0.5, linetype ="dashed") +
    geom_vline(
    aes(xintercept = quantile(ATE_boot, 0.975)),
    color = "slateblue1", linewidth = 0.5, linetype ="dashed") +
  theme(panel.background = element_blank(),
        plot.title = element_text(face = "bold", hjust = 0.5),
        axis.line = element_line(colour = 'black', linewidth = 0.5))

OR_plot <- ggplot(boots_df, aes(x = OR)) +
  geom_histogram(bins = 20, fill = "grey85") +
  labs(title = "Bootstrap OR",
       x = "Odds Ratio",
       y = NULL) +
  geom_vline(
    aes(xintercept = mean(OR_boot)),
    color = "tomato4", linewidth = 0.5) +
  geom_vline(
    aes(xintercept = quantile(OR_boot, 0.025)),
    color = "tomato1", linewidth = 0.5, linetype ="dashed") +
    geom_vline(
    aes(xintercept = quantile(OR_boot, 0.975)),
    color = "tomato1", linewidth = 0.5, linetype ="dashed") +
  theme(panel.background = element_blank(),
        plot.title = element_text(face = "bold", hjust = 0.5),
        axis.line = element_line(colour = 'black', linewidth = 0.5))

wrap_plots(list(ATE_plot, OR_plot))
```

```{r summary results}
# Create a summary data frame
results_table <- data.frame(
  Metric = c("Average Treatment Effect (ATE)", "Odds Ratio (OR)"),
  Estimate = c(mean(ATE_boot, na.rm = TRUE), mean(OR_boot, na.rm = TRUE)),
  Lower_CI = c(quantile(ATE_boot, 0.025, na.rm = TRUE), quantile(OR_boot, 0.025, na.rm = TRUE)),
  Upper_CI = c(quantile(ATE_boot, 0.975, na.rm = TRUE), quantile(OR_boot, 0.975, na.rm = TRUE))
)

# Format for display
results_table$Formatted <- sprintf("%.3f (95%% CI: %.3f, %.3f)", 
                                   results_table$Estimate, 
                                   results_table$Lower_CI, 
                                   results_table$Upper_CI)

print(results_table[, c("Metric", "Formatted")])
```
## Missing data


```{r}
#------------------Data wrangling on incomplete data--------------------------------------------------------------------
obesity_incomplete = get(load("obesity.Rda"))


# Mutate to binary 
obesity_incomplete = obesity_incomplete %>%
  mutate(medhyper = case_when(
    medhyper == "no" ~ 0,
    medhyper == "yes" ~ 1,),
    CVD = case_when(
      CVD == "No" ~ 0,
      CVD == "Yes" ~ 1,))

## Transform variables 

# Adiposity
plot(obesity_incomplete$bmi, obesity_incomplete$waist)
adiposity_model <- lm(bmi ~ waist, data = obesity_incomplete)
summary(adiposity_model)

obesity_incomplete$adiposity <- scale(obesity_incomplete$bmi) + scale(obesity_incomplete$waist)

# make Adiposity a numeric vector
obesity_incomplete$adiposity = as.numeric(scale(obesity_incomplete$bmi)) + as.numeric(scale(obesity_incomplete$waist))

# BP
plot(obesity_incomplete$SYSBP, obesity_incomplete$DIABP)
bp_model <- lm(SYSBP ~ DIABP, data = obesity_incomplete)
summary(bp_model)

obesity_incomplete$MAP <- obesity_incomplete$DIABP + (obesity_incomplete$SYSBP - obesity_incomplete$DIABP)/3
dev.off()

#-----------------NA pattern visualization ------------------------------------------------------------------

missing_pattern = md.pattern(obesity_incomplete)
missing_pattern

aggr(obesity_incomplete, numbers = TRUE, sortVars = TRUE)
# (diabetes - CVD - angina - death) are the variables where we find NAs together consistently



# -------------------testing--------------------------------
#test whether the data is MCAR (apparently you can only do this when data is normally distributed...)

test = mcar_test(obesity_incomplete)
print(test) # is significant --> not MCAR

obesity_incomplete$miss_CVD = is.na(obesity_incomplete$CVD)


# see if missingness depends on other variables
model = glm(miss_CVD ~ medhyper + 
            age + sex + adiposity + MAP + current.smoking +
            alcohol + medstatin + medglucose,
            data = obesity_incomplete, family = binomial)
 
# missingness depends on other variables (age, sex) --> MAR?
 summary(model)
 
# check if missingness is related to age
ggplot(obesity_incomplete, aes(x = factor(miss_CVD), y = age)) +
  geom_boxplot() + labs(x = "Missingness of CVD", 
                        y = "Age", 
                        title = "Age vs Missingness in CVD") +
                        scale_x_discrete(labels = c("Non-missing", "Missing"))

odds_age = exp(coef(model)['age'])
odds_age # for 1 increase of year the odds to get cvd increases by 7.9%

# so its plausible to assume that the missingness is due to increase in age

# Just remove the rows with NAs since its 2% of our data missing

```

```{r weighting}
library(survey)
library(cobalt)
# Fit propensity model with all covariates
propensity_model <- glm(medhyper ~ age + sex + current.smoking + alcohol + adiposity + 
                          MAP + SES + comorbidities,
                        family = binomial, 
                        data = obesity)
summary(propensity_model)

# Calculate propensity
obesity$ps<-fitted.values(propensity_model)

# explore propensity
summary(obesity$ps)

# histogram
par(mfrow=c(2,1))
hist(obesity$ps[obesity$medhyper == 1], xlim=c(0,1),main="MedHyper", xlab="Propensity score")
hist(obesity$ps[obesity$medhyper == 0], xlim=c(0,1),main="no MedHyper", xlab="Propensity score")

# weights
obesity$ipw <- ifelse(obesity$medhyper == 1, 1/obesity$ps, 1/(1-obesity$ps)) 
summary(obesity$ipw)

# check for balance
variables <- c("age", "sex", "current.smoking", "alcohol", "adiposity", "MAP", "SES", "comorbidities")
covariates <- obesity[, variables]
bal.tab(covariates, treat = obesity$medhyper, weights = obesity$ipw ,method = "weighting", un=TRUE)

#plot
love.plot(covariates, treat = obesity$medhyper, weights = obesity$ipw ,method = "weighting",
          binary = "std", threshold = .1)

# outcome table
table(obesity$CVD)


# weighted mean outcome in the treated
mean1.ipw <-weighted.mean(obesity$CVD[obesity$medhyper== 1], w=obesity$ipw[obesity$medhyper== 1])
mean1.ipw



# weighted mean outcome in the untreated
mean0.ipw <-weighted.mean(obesity$CVD[obesity$medhyper== 0], w=obesity$ipw[obesity$medhyper== 0])
mean0.ipw

# estimate of ATE
mean1.ipw-mean0.ipw


d.w <- svydesign(~1, weights = obesity$ipw, data = obesity)
fit.ipw <- svyglm(CVD ~ medhyper, design = d.w)
summary(fit.ipw)
# 95% CI
confint(fit.ipw)



# the 99 th percentile is
ipw2.p99 <-quantile(obesity$ipw,0.99)
ipw2.p99

obesity$ipw2.trunc <- ifelse(obesity$ipw>ipw2.p99, ipw2.p99, obesity$ipw)
summary(obesity$ipw2.trunc)


# and calculate the ATE with the truncated weights

d.w.trunc <- svydesign(~1, weights = obesity$ipw2.trunc, data = obesity)
fit.ipw.trunc <- svyglm(CVD ~ medhyper, design = d.w.trunc)
summary(fit.ipw.trunc)



# calculate numerator of stabilized weights (Pr(treatment ="RHC"))

numerator.model<-glm(medhyper ~ 1 , family = binomial,  data = obesity)

# Calculate PR(treatment =="RHC")
medhyper_yes <- fitted.values(numerator.model)
#stabilized weight
obesity$ipw2_stab <- ifelse(obesity$medhyper== 1, medhyper_yes/obesity$ps, (1-medhyper_yes)/(1-obesity$ps)) 
summary(obesity$ipw2_stab)
```

```{r matching}
library(MatchIt)
# 1:1 NN PS matching without replacement
match.out1 <- matchit(medhyper ~ age + sex + current.smoking + alcohol + adiposity + 
                          MAP + SES + comorbidities , data=obesity, method = "nearest", distance = "glm")

match.out1

summary(match.out1)

# w/ caliper and covariates
match.out2 <- matchit(medhyper ~ age + sex + current.smoking + alcohol + medstatin + medglucose + adiposity + 
                          MAP + SES + comorbidities, data=obesity, method = "nearest", distance = "glm", caliper = 0.1)

match.out2
summary(match.out2)

match.data <- match.data(match.out2)


table(match.data$medhyper, match.data$CVD) 
tab<- prop.table(table(match.data$medhyper, match.data$CVD) , margin=1)
tab

```






```{r weighting_book_code}
library(broom)
# Fit propensity model with all covariates
propensity_model <- glm(medhyper ~ age + sex + current.smoking + alcohol + adiposity + 
                          MAP + SES + comorbidities,
                        family = binomial, 
                        data = obesity)

# Add propensity scores to model
obesity_with_ps <- propensity_model %>%
  augment(type.predict = "response", data = obesity)


obesity_with_ps |>
  check_model_roc_curve(medhyper, .fitted) |>
  plot_model_roc_curve()

check_model_auc(
  obesity_with_ps,
  .exposure = medhyper,
  .fitted = .fitted
) 

# Not great AUC but "values between 0.6 and 0.8 usually indicate that we’ve picked up enough signal from the counfounders to use for adjustment but not so much that we have positivity issues"

# Plot mirrored histogram

ggplot(
  obesity_with_ps,
  aes(.fitted, fill = factor(medhyper))
) +
  geom_mirror_histogram(bins = 50) +
  scale_y_continuous(labels = abs) +
  labs(x = "propensity score", fill = "medhyper")
# Overlap is okish but balance is poor

# Check range of propensity score by group
obesity_with_ps |>
  group_by(medhyper) |>
  reframe(range = range(.fitted)) # range is okish

# look at the tails is to check the number of unexposed observations below the lowest probability for the exposed group and the number of exposed observations above the highest probability for the unexposed group
obesity_with_ps <- obesity_with_ps |>
  mutate(
    support = case_when(
      medhyper == 0 &
        .fitted < min(.fitted[medhyper == 1]) ~ "unexp_below",
      medhyper == 1 &
        .fitted > max(.fitted[medhyper == 0]) ~ "exp_above",
      .default = "inside_support",
      .ptype = factor(levels = c("unexp_below", "inside_support", "exp_above"))
    )
  ) 


obesity_with_ps |>
  count(support, .drop = FALSE)




# Check counts for extreme propensity scores on the left tail

obesity_with_ps |>
  count(medhyper, low_prob = .fitted <= .1)

# The majority of individuals with propensity scores ≤0.1 were untreated (1011 vs 68 treated), indicating the propensity model appropriately predicts treatment assignment. Only a small number of treated individuals had very low predicted probabilities of treatment.


# Add weights
library(propensity)

obesity_with_wt <- obesity_with_ps |>
  mutate(w_ate = wt_ate(.fitted, medhyper))



# Check for extreme weights
obesity_with_wt |>
  ggplot(aes(w_ate)) +
  geom_histogram() +
  scale_x_log10() +
  xlab("ATE Weights") # some weights above 10, will be an issue for stability

# Stabilise weights
obesity_with_wt <- obesity_with_ps |>
  mutate(stbl_wts = wt_ate(.fitted, medhyper, stabilize = TRUE))

obesity_with_wt |>
  summarize(
    mean = mean(stbl_wts),
    min = min(stbl_wts),
    max = max(stbl_wts),
    n = n(),
    sum = sum(stbl_wts)
  )

obesity_with_wt |>
  ggplot(aes(stbl_wts)) +
  geom_histogram() +
  scale_x_log10() +
  xlab("Stabilized ATE Weights") # still some extreme weights

# Stabilised AND truncated weights
obesity_with_wt <- obesity_with_wt |>
  mutate(
    trimmed_ps = ps_trim(.fitted, method = "adaptive") |>
      ps_refit(propensity_model),
    trunc_ps = ps_trunc(.fitted, method = "pctl", lower = .01, upper = 1)
  )

ggplot(
  obesity_with_wt ,
  aes(trunc_ps, fill = factor(medhyper))
) +
  geom_mirror_histogram(bins = 50) +
  scale_y_continuous(labels = abs) +
  labs(x = "propensity score", fill = "medhyper")

obesity_with_wt <- obesity_with_wt |>
  mutate(trunc_stbl_wt = wt_ate(
    trunc_ps,
    medhyper,
    stabilize = TRUE
  ))

obesity_with_wt |>
  ggplot(aes(trunc_stbl_wt)) +
  geom_histogram() +
  scale_x_log10() +
  xlab("Truncated and Stabilized ATE Weights")


#Ch9 of book

obesity_with_ps <-
  glm(
    medhyper ~ age + sex + current.smoking + alcohol + adiposity + MAP + SES + comorbidities,
    data = obesity,
    family = binomial()
 ) |>
  augment(type.predict = "response", data = obesity)

obesity_with_wt <- obesity_with_ps |>
  mutate(
    w_ate = wt_ate(.fitted, medhyper),
    medhyper = factor(medhyper)
 )


obesity_with_wt |>
  plot_mirror_distributions( 
    .exposure = medhyper,
    .var = .fitted,
    .weights = w_ate
 ) +
  labs(fill = "medhyper")


ggplot(
  obesity_with_wt,
  aes(.fitted, group = medhyper)
) +
  geom_mirror_histogram(
    aes(fill = factor(medhyper), weight = w_ate)
 ) +
  scale_y_continuous(labels = abs) +
  labs(
    x = "propensity score",
    fill = "medhyper"
 )

obesity_with_wt |>
  plot_mirror_distributions(
    .exposure = medhyper,
    .var = .fitted,
    .weights = w_ate
 ) +
  labs(fill = "medhyper")



obesity_with_wt |>
  check_model_roc_curve(
    medhyper,
    .fitted,
    .weights = w_ate
 ) |>
  plot_model_roc_curve()

check_model_auc(
  obesity_with_wt,
  .exposure = medhyper,
  .fitted = .fitted,
  .weights = w_ate
)


library(scales)
obesity_with_wt |>
  summarize(
    n = n(),
    ess_ate = ess(w_ate),
    percent_ess_ate = percent(ess_ate / n)
 )

obesity_with_wt |>
  group_by(medhyper) |>
  summarize(
    n = n(),
    ess_ate = ess(w_ate),
    percent_ess_ate = percent(ess_ate / n)
 )

ggplot(
  obesity_with_wt,
  aes(x = as.numeric(w_ate), fill = medhyper)
) +
  geom_density(color = NA) +
  scale_x_log10() +
  labs(x = "ATE weight", fill = "medhyper")


obesity_with_wt |>
  mutate(
    trunc_ps = ps_trunc(.fitted, method = "pctl", lower = .05, upper = .95),
    w_ate_trunc = wt_ate(trunc_ps, medhyper)
 ) |>
  summarize(
    n = n(),
    ess_ate_trunc = ess(w_ate_trunc),
    percent_ess_ate = percent(ess_ate_trunc / n)
 )

library(halfmoon)
balance_metrics <-
  obesity_with_wt |>
  check_balance(
    .vars = c("age", "sex", "current.smoking", "alcohol", "adiposity", "MAP", "SES", "comorbidities"),
    .exposure = medhyper,
    .weights = w_ate
 )

balance_metrics

smds <- balance_metrics |>
  filter(metric == "smd")

smds

vrs <- balance_metrics |>
  filter(metric == "vr")

vrs

ggplot(
  data = smds,
  aes(
    x = abs(estimate),
    y = variable,
    group = method,
    color = method
 )
) +
  geom_love()

ggplot(
  data = vrs,
  aes(
    x = estimate,
    y = variable,
    group = method,
    color = method
 )
) +
  geom_love(vline_xintercept = 1)

balance_metrics |>
  filter(metric %in% c("smd", "vr")) |>
  plot_balance(facet_scales = "free_x")

balance_metrics |>
  filter(metric == "ks")


balance_metrics_joint <-
  obesity_with_wt |>
  check_balance(
    .vars = c(age, sex, current.smoking, alcohol, adiposity, MAP, SES, comorbidities),
    .exposure = medhyper,
    .weights = w_ate,
    interactions = TRUE,
    squares = TRUE
 )

balance_metrics_joint |>
  filter(metric == "energy") |>
  select(method, estimate)
```