---
title: "week 4"
author: "Zoja Pleteršek"
date: "2026-02-24"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
obesity = read_csv("DF_mutated.csv")

data <- obesity %>%
  na.omit()
1-nrow(data)/nrow(obesity)

obesity = data
```

This should be all run on a clean dataset where (the dead are removed?) and where the MAP and adiposity are defined. 

# Identifying confounders

## T-tests
```{r}
t.test(obesity$age ~ obesity$medhyper) #significant
t.test(obesity$adiposity ~ obesity$medhyper) #significant
t.test(obesity$MAP ~ obesity$medhyper) #significant
```

## Chi square 
```{r}
chisq.test(obesity$sex, obesity$medhyper) #significant 
chisq.test(obesity$current.smoking, obesity$medhyper) #not significant 
chisq.test(obesity$alcohol, obesity$medhyper) #significant 
chisq.test(obesity$medstatin, obesity$medhyper) #significant
chisq.test(obesity$medglucose, obesity$medhyper) #significant 
```



# Outcome regression
```{r}
glm = glm(CVD ~ medhyper + 
            age + medhyper*age +
            sex + medhyper*sex +
            adiposity + medhyper*adiposity + 
            MAP + medhyper*MAP +
            current.smoking + medhyper*current.smoking +
            alcohol + current.smoking*alcohol +
            medstatin +  medhyper*medstatin +
            medglucose + medhyper*medglucose, 
          data = obesity, family = binomial)
summary(glm)
```


# G-formula
## Step 1
```{r}
g_model = glm(CVD ~ medhyper + 
            age + medhyper*age +
            sex + medhyper*sex +
            adiposity + medhyper*adiposity + 
            MAP + medhyper*MAP +
            current.smoking + medhyper*current.smoking +
            alcohol + current.smoking*alcohol +
            medstatin +  medhyper*medstatin +
            medglucose + medhyper*medglucose, 
          data = obesity, family = binomial)
summary(g_model)
```

## Step 2
```{r}
obesity1 = obesity
obesity1$medhyper = 1
YE1 = predict(g_model, newdata = obesity1, type="response")
mean_YE1 = mean(YE1, na.rm = T)
```


```{r}
obesity0 = obesity
obesity0$medhyper = 0
YE0 = predict(g_model, newdata = obesity0, type="response")
mean_YE0 = mean(YE0, na.rm = T)

```

## Step 3
```{r}
mean_YE1- mean_YE0 #average treatment effect (ATE)

(mean_YE1/(1-mean_YE1))/(mean_YE0/(1-mean_YE0)) #causal odds ratio
```


# Bootstrap to get the CI
```{r}
set.seed(123)
B = 1000
ATE_boot = numeric(B)
OR_boot  = numeric(B)

n = nrow(obesity)

for (b in 1:B) {

  #Resample data
  index = sample(1:n, n, replace = TRUE) 
  data_b = obesity[index, ] 

  #Refit model
  g_model_b = glm(CVD ~ medhyper + 
            age + medhyper*age +
            sex + medhyper*sex +
            adiposity + medhyper*adiposity + 
            MAP + medhyper*MAP +
            current.smoking + medhyper*current.smoking +
            alcohol + current.smoking*alcohol +
            medstatin +  medhyper*medstatin +
            medglucose + medhyper*medglucose, 
          data = data_b, family = binomial)

  #Predict medhyper = 1
  data1 = data_b
  data1$medhyper = 1
  p1 = predict(g_model_b, newdata = data1, type="response")
  m1 = mean(p1, na.rm = T)

  #Predict medhyper = 0
  data0 = data_b
  data0$medhyper = 0
  p0 = predict(g_model_b, newdata = data0, type="response")
  m0 = mean(p0, na.rm = T)

  #Store estimands
  ATE_boot[b] = m1 - m0
  OR_boot[b]  = (m1/(1-m1)) / (m0/(1-m0))
}

mean(ATE_boot, na.rm = T)
mean(OR_boot, na.rm = T)

quantile(ATE_boot, c(0.025, 0.975), na.rm = T)
quantile(OR_boot,  c(0.025, 0.975), na.rm = T)
```

## Positivity
```{r}
table(obesity$sex, obesity$medhyper)
table(obesity$current.smoking, obesity$medhyper)
table(obesity$alcohol, obesity$medhyper)
table(obesity$medstatin, obesity$medhyper)
table(obesity$medglucose, obesity$medhyper)
```
## Visualization

```{r}
par(mfrow=c(1,2)) # Side-by-side plots

# ATE Histogram
hist(ATE_boot, breaks=20, main="Bootstrap ATE", xlab="Risk Difference", col="gray")
abline(v = mean(ATE_boot), col="red", lwd=2)
abline(v = quantile(ATE_boot, c(0.025, 0.975)), col="red", lty=2)

# OR Histogram
hist(OR_boot, breaks=20, main="Bootstrap OR", xlab="Odds Ratio", col="gray")
abline(v = mean(OR_boot), col="red", lwd=2)
abline(v = quantile(OR_boot, c(0.025, 0.975)), col="red", lty=2)
```

```{r}
# Create a summary data frame
results_table <- data.frame(
  Metric = c("Average Treatment Effect (ATE)", "Odds Ratio (OR)"),
  Estimate = c(mean(ATE_boot, na.rm = TRUE), mean(OR_boot, na.rm = TRUE)),
  Lower_CI = c(quantile(ATE_boot, 0.025, na.rm = TRUE), quantile(OR_boot, 0.025, na.rm = TRUE)),
  Upper_CI = c(quantile(ATE_boot, 0.975, na.rm = TRUE), quantile(OR_boot, 0.975, na.rm = TRUE))
)

# Format for display
results_table$Formatted <- sprintf("%.3f (95%% CI: %.3f, %.3f)", 
                                   results_table$Estimate, 
                                   results_table$Lower_CI, 
                                   results_table$Upper_CI)

print(results_table[, c("Metric", "Formatted")])
```



